[tool.poetry]
name = "pythonpkgs"
version = "0.1.0"
description = ""
authors = ["Christopher Fredén <me@icetan.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "=3.11.*"
aider-chat = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
